apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin-binding
  namespace: python-app
subjects:
- kind: User
  name: nesnukurian@gmail.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: Baljitk024@gmail.com
  apiGroup: rbac.authorization.k8s.io  
- kind: User
  name: akash011nahak@gmail.com
  apiGroup: rbac.authorization.k8s.io   
- kind: User
  name: harkaur02@gmail.com
  apiGroup: rbac.authorization.k8s.io  
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
